version: "3"
services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      - GRAPHQL_HOST=graphql
      - GRAPHQL_PORT=9010
  graphql:
    build: ../release-status-graphql
    ports:
      - "9010:9010"
    volumes:
      - ${CONFIG_FILE}:/src/config/default.json
    links:
      - redis
  redis:
    image: redis
